### ISSUE TITLE
Move test fixtures and utils into someplace that's a little easier to access

### ISSUE THREAD

**Issue by charlieduong94** [JupiterOne/sdk#111]
It would nice to be able to access the utilities without having to dig into other `__tests__` directories.

There's a simple trick that can be done to have node resolve the directory without having to muck with `require` (see this [test](https://github.com/JupiterOne/graph-trend-micro/blob/master/src/steps/fetch-computers/__tests__/index.test.ts#L5) and this [directory](https://github.com/JupiterOne/graph-trend-micro/tree/master/test))

Once we move to a monorepo, we could just put the utils and fixtures in a separate package that won't be published.

**Comment by aiwilliams** [comment]
> Once we move to a monorepo, we could just put the utils and fixtures in a separate package that won't be published.

Yes! I was looking at the jest monorepo, and they use this technique. Also, note that `__test__` is kind of an adopted standard; I noticed it was the default for a few tools as I was setting up the other monorepo.

**Comment by aiwilliams** [comment]
I think this is done by https://github.com/JupiterOne/sdk/tree/master/packages/integration-sdk-private-test-utils. Please re-open with more details on what needs to happen.
