### ISSUE TITLE
Recorded responses are stored as gzip, cannot do PR reviews for sensitive content

### ISSUE THREAD

**Issue by aiwilliams** [JupiterOne/sdk#117]
It isn't possible during pull request reviews to see if there is sensitive information in the responses. There are a couple projects doing decompression:

* https://github.com/JupiterOne/graph-azure/blob/master/test/helpers/polly.ts#L25
* https://github.com/JupiterOne/graph-snowflake/blob/master/test/index.ts#L54

Generally speaking, it would be necessary to look at the response encoding and when possible, decode and store UTF-8 text. It will be important that when the recordings are replayed, they still work.

**Comment by VDubber** [comment]
This is now available within the @jupiterone/integration-sdk-testing package. 
```
return setupRecording({
    ...
    mutateEntry: mutations.unzipGzippedRecordingEntry
});
```

`mutations.unzipGzippedRecordingEntry(entry);` provides this capability.
