### ISSUE TITLE
Move eslint, tsconfig, husky, etc. into shareable package

### ISSUE THREAD

**Issue by philidem** [JupiterOne/sdk#128]
After moving to a monorepo (#126) we should make sure the configuration for development tooling is moved to a shareable package.

**Comment by aiwilliams** [comment]
It think this would be superb. What do you think of naming the package `integration-toolchain` 😁

**Comment by aiwilliams** [comment]
This is done by https://github.com/JupiterOne/sdk/tree/master/packages/integration-sdk-dev-tools. Please re-open if there are things still missing.
