### ISSUE TITLE
Do not use ts-node in deployed environment

### ISSUE THREAD

**Issue by philidem** [JupiterOne/sdk#139]
I see this in our logs at runtime:

`TypeScript files detected. Registering ts-node.`

We should not be using `ts-node` with our compiled integrations.

**Comment by charlieduong94** [comment]
With us moving away from directory loading, ts-node will only be used in the cli

**Comment by charlieduong94** [comment]
@softwarewright once you get the graph projects updated, can you close this?

**Comment by softwarewright** [comment]
This should be done now.
