### ISSUE TITLE
Report key metrics to a metrics service, including important dimensions

### ISSUE THREAD

**Issue by aiwilliams** [JupiterOne/sdk#142]
In order to support visibility into execution patterns, report key events to a metrics service. This should be an interface to different implementations, at least 2, one for local execution and in a managed execution environment, a cloud-native metrics service.

Each metric should include these dimensions:

* accountId
* integrationDefinitionId
* integrationInstanceId
* integrationJobId

Let's consider starting with these metrics:

* Time to execute each step within the integration
* Total time to complete an execution
* Number of executions

**Comment by aiwilliams** [comment]
@philidem says:
> We might want to consider logging out the metrics via bunyan and then analyze the logs with a lambda function. This will make it easy to publish metrics without impacting performance

**Comment by austinkelleher** [comment]
This issue has been fixed as part of multiple PRs.
