### ISSUE TITLE
Use source _type for mapped relationships when available

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/sdk#257]
Mapped relationships can be created using one of two interfaces: 

1. `MappedRelationshipOptions` (which includes `source: Entity;` prop
2. `MappedRelationshipLiteralOptions` (which includes `_mapping.sourceEntityKey: string;` prop

In both cases, the `createMappedRelationship()` function is used to generate the resulting `_type` property, and it uses a static `'mapping_source'` type as the source type, even if the source entity's `_type` is known.

We should add the source `_type` so that mapped relationships generate relationships like:
```azure_role_definition_assigned_user```
as opposed to 
```mapping_source_assigned_azure_user```

**Comment by aiwilliams** [comment]
Related: https://github.com/JupiterOne/sdk/issues/62

Now might be a good time to implement those `createEntityRelationship` and `createMappedRelationship` functions, with your proposal for the generated relationship `_type` value, and then we deprecate `createIntegrationEntity` (do not change it, the new functions should be adopted). What do you think?

cc/ @charlieduong94 @philidem @austinkelleher

**Comment by ndowmon** [comment]
I think that's a good proposal. What about `createDirectRelationship` instead of `createEntityReltionship`?

**Comment by aiwilliams** [comment]
> What about `createDirectRelationship` instead of `createEntityRelationship`? That matches the existing interfaces, and I think is all-around more clear.

Sounds great!
