### ISSUE TITLE
Export `@jupiterone/data-model` properties from `@jupiterone/integration-sdk-core`

### ISSUE THREAD

**Issue by austinkelleher** [JupiterOne/sdk#303]
Since we are pushing forward with encouraging users to reference `RelationshipClass`, it would be great if they could directly reference it from an exported variable in the SDK.

Proposal:

```typescript
import { RelationshipClass /* and other data-model properties too */ } from '@jupiterone/integration-sdk-core';
```

Alternatively, we could export a top-level `DataModel` property from the SDK:

```typescript
import { DataModel } from '@jupiterone/integration-sdk-core';
DataModel.RelationshipClass.HAS
```

Thoughts @aiwilliams @ndowmon?

**Comment by ndowmon** [comment]
I don't have a strong opinion about whether or not to allow users to reference `RelationshipClass` directly from the SDK. At this point exporting from the data model directly seems alright to me.

Sort of related question is whether there is an argument to bring the `@jupiterone/data-model` package into the SDK itself.

I will say that if we _do_ bring these references into the SDK, I would strongly prefer the `import { RelationshipClass } from ... ` method over the `import { DataModel } from ...` and `DataModel.RelationshpClass.HAS`. To me, the latter does't offer any benefit over importing the data-model package directly.

**Comment by austinkelleher** [comment]
@ndowmon Great thoughts. I had similar thoughts as well. I chatted briefly with @aiwilliams and he brought up that maybe it makes sense to namespace `DataModel` instead of polluting the global `integration-sdk-core` namespace with every exported property in `@jupiterone/data-model`. In the future we plan to auto-generate typescript typings and perhaps runtypes for every class in the data model. Do those make sense to be exported at the top-level of the SDK?

Would you expect something like this?

```typescript
import { DataStore } from '@jupiterone/data-model';
```

The namespace'd API would look like this:

```typescript
import { DataModel } from '@jupiterone/data-model';
DataModel.DataStore
```

Of course, we could also add namespacing in the data-model package, but that doesn't really solve the verbose imports. I think we want to keep packages like the data-model as pure as possible.

As we export more top-level properties from the SDK, we also run the risk of naming collisions, which will cause us to introduce namespaces later or tweak naming to not collide.
