### ISSUE TITLE
`integration-sdk-testing` package's `findEntity` does not find initial entities defined in `createMockStepExecutionContext`

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/sdk#311]
The following test should pass, but instead `result === null`:

```typescript
test.only('jobState.findEntity() should work with initial entities', async() => {
  const targetEntity: Entity = {
    _key: 'entity-key',
    _type: 'entity_type',
    _class: 'Entity',
  }
  const context = createMockStepExecutionContext({
    instanceConfig: {}, 
    entities: [targetEntity],
  });

  const result = await context.jobState.findEntity('entity_key');

  expect(result).toBe(targetEntity);
});
```

**Comment by aiwilliams** [comment]
I'd like to see whether we can work toward having the mock context contain an actual JobState (the same implementation that is used at runtime), just change out the object store from file-based to in-memory. This is I think the 4th time we've had different behavior in testing get us.

**Comment by austinkelleher** [comment]
Great find. Thanks for opening this issue. I agree with Adam, it would be really awesome if we could leverage the same `JobState` implementation with a different object store.
