### ISSUE TITLE
Expand `jobState.findEntity()` interface to match case-insensitive IDs

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/sdk#355]
Some integrations return case-insensitive IDs that need to be mapped back to entities that exist in the job state. The SDK should make the `findEntity` methods more flexible to meet these needs.

Possible implementations:
```typescript
// with options argument
findEntity: (_key: string, options?: { matchCaseInsensitive?: boolean }) => Promise<Entity | null>;
// with regex
findEntity: (_key: string | RegExp) => Promise<Entity | null>;
// future... with regex or callback?
findEntity: ((_key: string | RegExp) => Promise<Entity | null>) | ((callback: (_key: string) => boolean) => Promise<Entity | null>;
```

**Comment by austinkelleher** [comment]
Can you give an example of this? I think it is much more desired to have keys always be predictable. The behavior of our key tracking strategy in the SDK should match the strategy of the backend. How do you handle the case that there are multiple keys that match a specific case-insensitive pattern. 

For example these 3 entities:

- abc
- aBc
- aBC

**Comment by ndowmon** [comment]
@austinkelleher for example, Azure security scans create a link between a scan and a target resource, but azure lowercases the target resource in a SecurityAssessment:

```typescript
// azure security scan
const data: SecurityAssessment = {
  id:
    '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7/resourcegroups/j1dev/providers/microsoft.storage/storageaccounts/ndowmon1j1devblobstorage/providers/Microsoft.Security/assessments/51fd8bb1-0db4-bbf1-7e2b-cfcba7eb66a6',
  name: '51fd8bb1-0db4-bbf1-7e2b-cfcba7eb66a6',
  type: 'Microsoft.Security/assessments',
  displayName: 'Storage account public access should be disallowed',
  status: { code: 'Unhealthy' },
  resourceDetails: ({
    Source: 'Azure',
    Id:
      '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7/resourcegroups/j1dev/providers/microsoft.storage/storageaccounts/ndowmon1j1devblobstorage',
  },
};

// storage account ID
id: '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7/resourceGroups/j1dev/providers/Microsoft.Storage/storageAccounts/ndowmon1j1devblobstorage';
```

I would propose making no changes to the duplicate key tracker, causing no change in case `abc`, `aBc`, and `aBC` are all added to a given `jobState`. It would only have to be handled when `findEntity(/abc/i)` is called. We could either log an error & return `undefined`, or else throw an error on trying to retrieve `/abc/i`, which would return 3 entities in this example.

**Comment by aiwilliams** [comment]
Can the Azure integration normalize the values for the `_key` property? It does seem to me that this is a problem for the integration to handle, since the provider is the domain of the integration. The SDK is working for JupiterOne, which deals (I think) with case sensitive `_key` values. If Azure is case insensitive, then we could just down case the `_key` values, and down case any Azure key value anywhere it's placed into an entity?

**Comment by ndowmon** [comment]
Per conversation with @aiwilliams earlier today, a better impl here would be to introduce an optional transformer to the key tracker.
