### ISSUE TITLE
Introduce `beforeAddEntity` hook into `IntegrationInvocationConfig`

### ISSUE THREAD

**Issue by austinkelleher** [JupiterOne/sdk#470]
Sometimes you want to be able to add a specific property to _all_ entities. This can add a significant amount of code churn to a project. It would be great if there is a hook that could be exposed and called before an entity is added to the job state via `jobState.addEntity` or `jobState.addEntities`.

In the https://github.com/jupiterone/graph-google-cloud project, we would like to add the `projectId` property to all entities, but there isn't an easy method of doing that without changing a lot of code in the project.

Example usage:

```typescript
export const invocationConfig: IntegrationInvocationConfig<IntegrationConfig> = {
  instanceConfigFields: {},
  integrationSteps: [],

  beforeAddEntity(context: IntegrationStepContext, entity: Entity): Entity {
    const projectId = context.instance.config.projectId;

    return {
      ...entity,
      projectId: entity.projectId || projectId
    };
  }
};
```

**Comment by ndowmon** [comment]
FWIW I'd be interested in understanding the reason behind extending the `invocationConfig` interface in this way. It seems like it would have been just as easy to export a project-specific function for `createIntegrationEntity()` to do this same behavior:

```typescript
// src/converter.ts
function createGoogleCloudIntegrationEntity(
  input: IntegrationEntityBuilderInput,
  context: IntegrationStepContext,
) {
  const entity = createIntegrationEntity(input);
  return {
    ...entity,
    projectId: entity.projectId || context.instance.config.projectId,
  }
}

// src/steps/buckets/converters.ts

function createGoogleCloudBucketEntity(
  bucket: Bucket,
  context: IntegrationStepContext
) {
  return createGoogleCloudIntegrationEntity(
    entityData: {
      source,
      assign: { ... }
    }
  )
}
```

I get that it'd take more find + replace to change this across the whole project, but it doesn't seem like more work than opening a PR in the SDK/versioning/bumping in google cloud etc.
