### ISSUE TITLE
Provide list of properties transferred for each entity/relationship in the integration documentation

### ISSUE THREAD

**Issue by mknoedel** [JupiterOne/sdk#487]
### Problem

The only way for JupiterOne users to know what properties an entity or relationship will have is for them to go to the converter files in the graph projects. This makes it difficult for users to write J1QL queries as they do not know what to query for.

### Solution

Provide a schema or a list of properties per _type in the integration documentation. There are several ways this could be done which should be discussed in the comments of this issue.

### Relates To
#449

**Comment by charlieduong94** [comment]
ATM with how we store some entity data in J1, it shouldn't be too difficult to generate a schema from one of our data stores to assist with making J1QL queries easier to write. There's some prior art here with how entity properties are listed in the asset inventory app that can possibly be leveraged/improved upon. Some bigger changes would need to be made to support the same functionality with relationships though.
