### ISSUE TITLE
Add an additional type of error for when we exceed retries/quotas

### ISSUE THREAD

**Issue by eXtremeX** [JupiterOne/sdk#673]
## Problem

Errors such as _"Quota exceeded for quota metric XXX"_ (and similar for other providers) that happen once we couldn't fetch the resources even after exhausting all the retries (with exponential backoff) have a big impact on Sentry and we can easily exceed the error/transaction limits thanks to them.

It'd be great if we could not report them to Sentry (e.g. [shouldReportErrorToOperator(err) ](https://github.com/JupiterOne/jupiter-managed-integration/blob/d20cc12218b272a55b5627ac57492210136889bf/packages/runtime/src/executeIntegration.ts#L185)should return `false` for them).

We could introduce a new type for them, here are some ideas:

**IntegrationProviderRateExhaustedError**
```ts
code: 'PROVIDER_RATE_EXHAUSTED_ERROR',
message: `Provider rate exhausted at ${options.endpoint}: ${options.status} ${options.statusText}`
```

**IntegrationProviderQuotaExceededError**
```ts
code: 'PROVIDER_QUOTA_EXCEEDED_ERROR',
message: `Provider quota exceeded at ${options.endpoint}: ${options.status} ${options.statusText}`,
```

**IntegrationProviderRetriesExceededError**
```ts
code: 'PROVIDER_RETRIES_EXCEEDED_ERROR',
message: `Provider retries exceeded at ${options.endpoint}: ${options.status} ${options.statusText}`,
```

Looking forward to opinions as well as name suggestions!

**Comment by aiwilliams** [comment]
Thanks, @eXtremeX! I'm excited about this being implemented.

I think I would vote for `PROVIDER_RETRIES_EXCEEDED_ERROR` because it reflects the fact that we're just not going to try again. I don't know that we can say in every case that the reason we are not going to retry is that rate limits or quotas were exceeded.

**Comment by VDubber** [comment]
I agree with @aiwilliams. PROVIDER_RETRIES_EXCEEDED_ERROR is generic but also clear. 
Would it be worth trying to include in the error some specifics around the retries? For example, GitHub has primary and secondary rate limits and also a rate limit reset timestamp. Maybe, we could allow a flexible `retryDetails` parameter in the exception?

**Comment by mdaum** [comment]
Also like `PROVIDER_RETRIES_EXCEEDED_ERROR`. As for `retryDetails`, is this meant to encapsulate any retry-related detail we receive from the api we are consuming? Or our request libraries retry options? I think the former has value as an optional argument, and should probably be of type `any`, as we will likely see widely varying contents depending on integration.

**Comment by austinkelleher** [comment]
@eXtremeX I'm going to close this out. Feel free to re-open if there are additional changes that we still need to make. Thanks for the issue and contribution!
