### ISSUE TITLE
Support supplying an API base URL in CLI commands

### ISSUE THREAD

**Issue by austinkelleher** [JupiterOne/sdk#674]
# Problem

Now that we have additional environments that JupiterOne is deployed to, we need a mechanism for synchronizing data against alternative hosts.

# Proposal

Each entrypoint in the SDK should support supplying an API base URL that is ultimately leveraged during uploads. Consider the following entrypoints...

## `j1-integration sync`

The `sync` CLI command could take an optional `--api-base-url` argument such as `https://api.us.jupiterone.io` (also the default)

Example usage:

```
j1-integration sync --api-base-url "https://api.us.jupiterone.io"
```

## `j1-integration run`

The `run` CLI command could take an optional `--api-base-url` argument such as `https://api.us.jupiterone.io` (also the default)

Example usage:

```
j1-integration run --api-base-url "https://api.us.jupiterone.io"
```

## `j1-integration validate-question-file`

The `validate-question-file` CLI command could take an optional `--api-base-url` argument such as `https://api.us.jupiterone.io` (also the default)

Example usage:

```
j1-integration validate-question-file --api-base-url "https://api.us.jupiterone.io"
```

# Acceptance Criteria

- Each entrypoint into the SDK supports accepting an API base URL
- Automated tests have been written to validate each new API change and manual tests have been run to validate the behavior against a real environment
- Documentation has been updated to reflect the new API changes
- We also support a `--development` flag in some CLI commands. If a `--development` flag is supplied _and_ an `--api-base-url` flag is supplied, we should throw a fatal CLI error (invalid configuration supplied)

# Additional Considerations

There is also a `j1` CLI in the project (sub-package `@jupiterone/cli`) that exposes `import` and `export` commands. We should also support `--api-base-url` using those CLI commands, but it is out of the scope of this task. I will create additional issues to track supporting those features.

**Comment by adam-in-ict** [comment]
So we should throw an invalid config error when --development and --api-base-url are specified together.  What about when  the JUPITERONE_DEV environment variable is specified?  

I was leaning towards allowing users to specify both and just note in documentation that specifying --api-base-url will override any URLs set by --development or otherwise.

**Comment by austinkelleher** [comment]
@adam-in-ict I think throwing when properties that are not compatible are supplied. When `--api-base-url` is supplied, there is no development environment that we can reason about. No user should ever want to supply both properties anyway.

**Comment by adam-in-ict** [comment]
API base URL support added in version 8.8.1.
