### ISSUE TITLE
Convert project into a monorepo

### ISSUE THREAD

**Issue by charlieduong94** [JupiterOne/sdk#92]
Switching to a monorepo will help keep testing and cli code out of the final package/bundle that we hope to use in deployed environments while still keeping packages nicely in sync.

The code is already pretty well segregated so creating separate packages should be pretty easy.
```
src/cli -> @jupiterone/integration-sdk-cli
src/framework -> @jupiterone/integration-sdk (or maybe @jupiterone/integration-sdk-core?)
src/testing -> @jupiterone/integration-sdk-testing
```

**Comment by aiwilliams** [comment]
I like your suggestion @charlieduong94 of `@jupiterone/integration-sdk-core`. It makes it clear that there is more to it.
